AWSTemplateFormatVersion: '2010-09-09'
Description: VPC para Franquicia API

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub franquicia-vpc-${Environment}

  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  SubnetPrivateA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  SubnetPrivateB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetPublicAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublicA
      RouteTableId: !Ref PublicRouteTable

  SubnetPublicBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublicB
      RouteTableId: !Ref PublicRouteTable

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group para RDS
      SubnetIds:
        - !Ref SubnetPrivateA
        - !Ref SubnetPrivateB

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub franquicia-vpc-id-${Environment}
  SubnetPublicA:
    Value: !Ref SubnetPublicA
    Export:
      Name: !Sub franquicia-subnet-public-a-${Environment}
  SubnetPublicB:
    Value: !Ref SubnetPublicB
    Export:
      Name: !Sub franquicia-subnet-public-b-${Environment}
  SubnetPrivateA:
    Value: !Ref SubnetPrivateA
    Export:
      Name: !Sub franquicia-subnet-private-a-${Environment}
  SubnetPrivateB:
    Value: !Ref SubnetPrivateB
    Export:
      Name: !Sub franquicia-subnet-private-b-${Environment}
  RDSSubnetGroup:
    Value: !Ref RDSSubnetGroup
    Export:
      Name: !Sub franquicia-rds-subnet-group-${Environment}