AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager para Franquicia API

Parameters:
  Environment:
    Type: String
    Default: dev
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /accenture/${Environment}/db-credentials
      Description: Credenciales RDS Franquicia API
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "${DBPassword}",
          "port": "3306",
          "dbname": "franquicia_db"
        }

Outputs:
  DBSecretArn:
    Value: !Ref DBSecret
    Export:
      Name: !Sub franquicia-db-secret-arn-${Environment}